version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: golang
    ports:
      - 5432:5432
    volumes:
      - postgres-vol:/var/lib/postgresql/data 
      # copy the sql script to create tables
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # --save 20 1 which instructs the server to save 1 or more writes every 20 seconds to disk in case the server restarts. 
    # --requirepass parameter to add authentication with the password to read/write data on the Redis server
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-vol:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes:
  postgres-vol:
    name: postgres-volume
  redis-vol:
    name: redis-volume